# Generated by Django 3.2.15 on 2022-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='FF', max_length=8, null=True, verbose_name='HEX code'),
        ),
    ]
