# Generated by Django 3.2.15 on 2022-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Must-fill form. Max 254 letters.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Must-fill form. From 1 to 150 letters.', max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Must-fill form. From 1 to 150 letters.', max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Must-fill form. From 1 to 150 letters.', max_length=150, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Must-fill form. From 1 to 150 letters.', max_length=150, unique=True, verbose_name='Unique username'),
        ),
    ]
